title: Awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description for the new site here. 

# social links
twitter_username: your-twitter-h
github_username:  your-github-h

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
